services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    environment:
      DB_POSTGRESDB_HOST: <host>
      DB_TYPE: postgresdb
      DB_POSTGRESDB_PASSWORD: <pass>
      DB_POSTGRESDB_DATABASE: <db>
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: <user>
      DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: false